"""Repro-test generation — ARCHITECTURE.md §7 ("generate/locate a repro test and
confirm it fails"), INTERFACES.md §2 (``FixRecord.repro_test``).

A repro test is a **property check on the artifact**, not on VibeGuard. It re-reads the
target file from disk and asserts that one specific defect is absent — by parsing the
file with the standard library's :mod:`ast` for Python, or by scanning instructions for
a Dockerfile. It therefore fails while the defect is present and passes once the defect
is repaired, and it keeps working after VibeGuard is uninstalled: the generated file
imports nothing from ``vibeguard``.

Three properties make this safe to gate a fix on:

* **Per-finding, not per-file.** Every generated test is anchored to the normalised
  snippet the finding was created from. A second, unrepaired defect of the same rule in
  the same file has a different snippet (a fingerprint is
  ``rule|path|normalised-snippet``, so identical text *is* the same finding), so it
  cannot make this test fail and cannot cause a good fix to be rolled back.
* **Confirmed before it is trusted.** The runner insists the test *fails* before the
  patch is applied. A generated test that passes on the unrepaired code is not a
  reproduction of anything, so it is discarded rather than used as evidence.
* **Deterministic, no LLM.** Generation is templated per rule id. A rule with no
  template is skipped silently; nothing about the fix status changes.
"""

from __future__ import annotations

import re
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import PurePosixPath

from vibeguard.core.fingerprint import normalize
from vibeguard.core.models import Finding

__all__ = [
    "REPRO_DIRNAME",
    "ReproTest",
    "generate_repro_test",
    "repro_path",
    "supported_rule_ids",
]

#: Where generated tests live, relative to the repository root. Inside ``.vibeguard/``
#: so they are excluded from scanning by default and never committed by the fixer.
REPRO_DIRNAME = ".vibeguard/repro"


@dataclass(frozen=True)
class ReproTest:
    """A generated pytest module reproducing exactly one finding."""

    path: str
    content: str
    rule_id: str
    finding_id: str
    #: What the test asserts, in one line — used in reports and commit messages.
    describes: str


def _slug(rule_id: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", rule_id.lower()).strip("_")


def repro_path(finding: Finding) -> str:
    """``.vibeguard/repro/test_vg_<ruleid>_<fp12>.py`` for ``finding``."""
    return f"{REPRO_DIRNAME}/test_{_slug(finding.rule_id)}_{finding.fingerprint[:12]}.py"


# --------------------------------------------------------------------- template


_PRELUDE = '''\
"""Repro test for {rule_id} — generated by VibeGuard. Do not edit.

{title}

{summary}

This file is a property check on `{target}` itself: it re-reads the file from disk and
inspects it, so it fails while the defect is present and passes once it is repaired.
It imports nothing from vibeguard and keeps working on its own.
"""

from __future__ import annotations

import pathlib
import re

RULE_ID = {rule_id!r}
FINDING_ID = {finding_id!r}
TARGET = {target!r}
#: Whitespace-stripped, lowercased text of the defect as first detected. It anchors
#: this test to one occurrence, so an unrelated defect of the same kind in the same
#: file cannot fail it.
SNIPPET = {snippet!r}

ROOT = pathlib.Path(__file__).resolve().parents[2]
PATH = ROOT / TARGET


def normalise(text: str) -> str:
    return re.sub(r"\\s+", "", text).lower()


def source() -> str:
    return PATH.read_text(encoding="utf-8", errors="replace")


def is_the_reported_one(text: str) -> bool:
    """True when ``text`` is the very occurrence this test was generated for."""
    if not SNIPPET:
        return True
    seen = normalise(text)
    return bool(seen) and (seen in SNIPPET or SNIPPET in seen)

{finder}

def test_{slug}_{short}() -> None:
    assert PATH.is_file(), f"{{TARGET}} is missing — cannot check {{RULE_ID}}"
    defects = defects_found()
    assert not defects, "{assertion}:\\n" + "\\n".join(f"  {{item}}" for item in defects)
'''


_AST_HELPERS = '''
import ast


def dotted_name(node: ast.AST) -> str:
    """``requests.get`` for an Attribute chain, ``urlopen`` for a bare Name, else ""."""
    parts: list[str] = []
    while isinstance(node, ast.Attribute):
        parts.append(node.attr)
        node = node.value
    if isinstance(node, ast.Name):
        parts.append(node.id)
    elif parts:
        parts.append("?")
    else:
        return ""
    return ".".join(reversed(parts))


def tree_and_source() -> tuple[ast.Module, str]:
    text = source()
    return ast.parse(text), text
'''


_FINDER_HTTP_TIMEOUT = _AST_HELPERS + '''

HTTP_MODULES = {"requests", "httpx"}
HTTP_METHODS = {"get", "post", "put", "patch", "delete", "head", "options", "request"}


def defects_found() -> list[str]:
    """Outbound HTTP calls in the target that pass no ``timeout=``."""
    tree, text = tree_and_source()
    found: list[str] = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        name = dotted_name(node.func)
        module, _, method = name.rpartition(".")
        http = (module in HTTP_MODULES and method in HTTP_METHODS) or method == "urlopen"
        if not http:
            continue
        if any(keyword.arg == "timeout" for keyword in node.keywords):
            continue
        segment = ast.get_source_segment(text, node) or name
        if is_the_reported_one(segment):
            found.append(f"{TARGET}:{node.lineno}: {segment.splitlines()[0]}")
    return found
'''


_FINDER_TLS_VERIFY = '''

INSECURE = (
    re.compile(r"\\bverify\\s*=\\s*False\\b"),
    re.compile(r"\\brejectUnauthorized\\s*:\\s*false\\b"),
    re.compile(r"\\bCERT_NONE\\b"),
    re.compile(r"ssl\\._create_unverified_context"),
    re.compile(r"\\bstrictSSL\\s*:\\s*false\\b"),
    re.compile(r"InsecureSkipVerify\\s*:\\s*true"),
)


def defects_found() -> list[str]:
    """Lines that switch TLS certificate verification off."""
    found: list[str] = []
    for number, line in enumerate(source().splitlines(), start=1):
        if not any(pattern.search(line) for pattern in INSECURE):
            continue
        if is_the_reported_one(line.strip()):
            found.append(f"{TARGET}:{number}: {line.strip()}")
    return found
'''


_FINDER_UNSAFE_RANDOM = _AST_HELPERS + '''

def defects_found() -> list[str]:
    """Calls into the `random` module still producing the reported security value."""
    tree, text = tree_and_source()
    found: list[str] = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        name = dotted_name(node.func)
        if not (name == "random" or name.startswith("random.")):
            continue
        segment = ast.get_source_segment(text, node) or name
        if is_the_reported_one(segment):
            found.append(f"{TARGET}:{node.lineno}: {segment.splitlines()[0]}")
    return found
'''


_FINDER_SQLI_PYTHON = _AST_HELPERS + '''

EXECUTORS = {"execute", "executemany", "executescript", "raw", "execute_sql"}


def interpolation_kind(node: ast.AST) -> str:
    """How this argument was built, or "" when it is a safe constant/name."""
    if isinstance(node, ast.JoinedStr):
        return "an f-string"
    if isinstance(node, ast.BinOp) and isinstance(node.op, (ast.Mod, ast.Add)):
        return "string concatenation" if isinstance(node.op, ast.Add) else "%-formatting"
    if (
        isinstance(node, ast.Call)
        and isinstance(node.func, ast.Attribute)
        and node.func.attr == "format"
    ):
        return "str.format()"
    return ""


def defects_found() -> list[str]:
    """`execute(...)`-style calls whose SQL is still built by interpolation."""
    tree, text = tree_and_source()
    found: list[str] = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call) or not node.args:
            continue
        name = dotted_name(node.func)
        if name.rpartition(".")[2] not in EXECUTORS:
            continue
        argument = node.args[0]
        kind = interpolation_kind(argument)
        if not kind:
            continue
        segment = ast.get_source_segment(text, argument) or ""
        if is_the_reported_one(segment):
            found.append(
                f"{TARGET}:{node.lineno}: {name}(...) receives SQL built with {kind}"
            )
    return found
'''


_FINDER_SQLI_JS = '''

QUERY_CALL = re.compile(r"\\.\\s*(?:query|execute|exec|raw|all|get|run)\\s*\\(")
TEMPLATE_HOLE = re.compile(r"`[^`]*\\$\\{")
#: A quote followed by `+`, or `+` followed by a quote. \\x22/\\x27 keep the pattern
#: free of quote characters, which keeps this generated file easy to embed.
CONCATENATION = re.compile(r"[\\x22\\x27]\\s*\\+|\\+\\s*[\\x22\\x27]")
SQL_KEYWORD = re.compile(r"(?i)\\b(select|insert|update|delete|drop|union)\\b")


def defects_found() -> list[str]:
    """Driver calls whose SQL is still assembled from a template literal or `+`."""
    found: list[str] = []
    for number, line in enumerate(source().splitlines(), start=1):
        if not QUERY_CALL.search(line) or not SQL_KEYWORD.search(line):
            continue
        if not (TEMPLATE_HOLE.search(line) or CONCATENATION.search(line)):
            continue
        if is_the_reported_one(line.strip()):
            found.append(f"{TARGET}:{number}: {line.strip()}")
    return found
'''


_FINDER_DOCKER_USER = '''

USER_INSTRUCTION = re.compile(r"(?i)^\\s*USER\\s+(\\S+)")


def defects_found() -> list[str]:
    """The image still runs as root: no USER instruction, or only `USER root`."""
    users = [
        match.group(1)
        for match in (USER_INSTRUCTION.match(line) for line in source().splitlines())
        if match
    ]
    if not users:
        return [f"{TARGET} declares no USER instruction, so the container runs as root"]
    if all(user.lower() in {"root", "0"} for user in users):
        return [f"{TARGET} only ever switches to {users[-1]!r}, which is root"]
    return []
'''


_FINDER_DOCKER_HEALTHCHECK = '''

HEALTHCHECK = re.compile(r"(?i)^\\s*HEALTHCHECK\\s+(\\S+)")


def defects_found() -> list[str]:
    """The image declares no usable HEALTHCHECK."""
    directives = [
        match.group(1)
        for match in (HEALTHCHECK.match(line) for line in source().splitlines())
        if match
    ]
    if not directives:
        return [f"{TARGET} declares no HEALTHCHECK, so the runtime cannot tell it is up"]
    if all(directive.upper() == "NONE" for directive in directives):
        return [f"{TARGET} declares HEALTHCHECK NONE, which disables the probe"]
    return []
'''


@dataclass(frozen=True)
class _Template:
    finder: str
    summary: str
    assertion: str
    #: Suffixes the target file must have for this template to make sense.
    suffixes: tuple[str, ...] = ()
    #: Extra precondition on the finding.
    accepts: Callable[[Finding], bool] | None = None


def _is_dockerfile(finding: Finding) -> bool:
    name = PurePosixPath(finding.file or "").name.lower()
    return name.startswith("dockerfile") or name.endswith(".dockerfile")


#: Rule id → template. A rule that is not here has no repro test; that is a silent
#: skip and changes nothing about how its fix is classified.
TEMPLATES: dict[str, _Template] = {
    "VG-API-001": _Template(
        finder=_FINDER_HTTP_TIMEOUT,
        summary=(
            "Asserts, by parsing the module, that the reported outbound HTTP call "
            "passes an explicit `timeout=`. A call without one can block a worker "
            "forever."
        ),
        assertion="outbound HTTP call(s) still have no timeout",
        suffixes=(".py",),
    ),
    "VG-SEC-018": _Template(
        finder=_FINDER_TLS_VERIFY,
        summary=(
            "Asserts that the reported line no longer disables TLS certificate "
            "verification. Encryption without verification authenticates nobody."
        ),
        assertion="TLS certificate verification is still disabled",
    ),
    "VG-SEC-011": _Template(
        finder=_FINDER_UNSAFE_RANDOM,
        summary=(
            "Asserts, by parsing the module, that the reported security value is no "
            "longer generated from the predictable `random` module."
        ),
        assertion="a security value is still generated with the `random` module",
        suffixes=(".py",),
    ),
    "VG-SEC-001": _Template(
        finder=_FINDER_SQLI_PYTHON,
        summary=(
            "Asserts, by parsing the module, that the reported `execute(...)` call "
            "receives a parameterised statement rather than interpolated SQL."
        ),
        assertion="SQL is still built by interpolation inside an execute() call",
        suffixes=(".py",),
    ),
    "VG-SEC-002": _Template(
        finder=_FINDER_SQLI_JS,
        summary=(
            "Asserts that the reported driver call no longer assembles its SQL from a "
            "template literal or string concatenation."
        ),
        assertion="SQL is still built by interpolation inside a driver call",
        suffixes=(".js", ".jsx", ".mjs", ".cjs", ".ts", ".tsx"),
    ),
    "VG-CTR-001": _Template(
        finder=_FINDER_DOCKER_USER,
        summary=(
            "Asserts that the Dockerfile switches to an unprivileged USER, so a "
            "container escape does not start from root."
        ),
        assertion="the image still runs as root",
        accepts=_is_dockerfile,
    ),
    "VG-CTR-002": _Template(
        finder=_FINDER_DOCKER_HEALTHCHECK,
        summary=(
            "Asserts that the Dockerfile declares a HEALTHCHECK, so the runtime can "
            "tell a wedged container from a healthy one."
        ),
        assertion="the image declares no HEALTHCHECK",
        accepts=_is_dockerfile,
    ),
}


def supported_rule_ids() -> list[str]:
    """Rule ids a repro test can be generated for."""
    return sorted(TEMPLATES)


def generate_repro_test(finding: Finding) -> ReproTest | None:
    """Render the repro test for ``finding``, or ``None`` when unsupported.

    ``None`` means "no template for this rule, or the finding lacks what the template
    needs" — never an error. The caller carries on and fixes without a repro test.
    """
    template = TEMPLATES.get(finding.rule_id)
    if template is None or not finding.file:
        return None
    if template.suffixes and PurePosixPath(finding.file).suffix.lower() not in template.suffixes:
        return None
    if template.accepts is not None and not template.accepts(finding):
        return None

    snippet = finding.evidence[0].snippet if finding.evidence else ""
    short = finding.fingerprint[:12]
    content = _PRELUDE.format(
        rule_id=finding.rule_id,
        finding_id=finding.id,
        title=finding.title,
        summary=template.summary,
        target=finding.file,
        snippet=normalize(snippet),
        finder=template.finder,
        assertion=template.assertion,
        slug=_slug(finding.rule_id),
        short=short,
    )
    return ReproTest(
        path=repro_path(finding),
        content=content,
        rule_id=finding.rule_id,
        finding_id=finding.id,
        describes=template.assertion,
    )
